import './globals.css';
import { Poppins } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import StyledComponentsRegistry from '../lib/registry';
import { ThemeProvider } from '@/context/ThemeProvider';
import Main from './main';
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <ThemeProvider>
          <Main className={poppins.className}>{children}</Main>
        </ThemeProvider>
      </StyledComponentsRegistry>
    </html>
  );
}
